development:
  adapter: postgresql
  encoding: UTF8
  database: livingSocial_development
  host: localhost
test:
  adapter: postgresql
  encoding: UTF8
  database: livingSocial_testing
  host: localhost
production:
  adapter: postgresql
  encoding: UTF8
  database: livingSocial_production
  password: 
  host: localhost