development:
  adapter: postgresql
  encoding: UTF8
  database: livingSocial_development
  password: password
  host: localhost
production:
  adapter: postgresql
  encoding: UTF8
  database: livingSocial_production
  password: 
  host: localhost